#!/bin/bash

# Eisvogel template
# https://github.com/Wandmalfarbe/pandoc-latex-template
# https://afnan.io/post/2018-09-02-beautiful-pdfs-from-your-markdown-notes/
# Install required fonts: sudo apt install texlive-fonts-recommended texlive-fonts-extra

# https://pandoc.org/MANUAL.html#option--data-dir
#DATA_DIR=$HOME/.local/share/pandoc/
DATA_DIR=$HOME/.pandoc/
TEMPLATES=$DATA_DIR/templates # location of templates

pandoc "$1" \
    -f markdown \
    --template $TEMPLATES/eisvogel.tex \
    --include-in-header $TEMPLATES/no_centered_tables.tex \
    --listings \
    -V listings-disable-line-numbers:true \
    -V table-use-row-colors \
    -V linkcolor:blue \
    --pdf-engine=xelatex \
    -o "$2"

# Alternative for Eisvogel
# https://learnbyexample.github.io/tutorial/ebook-generation/customizing-pandoc/
#    -V linkcolor:blue \
#    -V geometry:a4paper \
#    -V geometry:margin=2cm \
#    -V mainfont="DejaVu Serif" \
#    -V monofont="DejaVu Sans Mono" \
#    --include-in-header $TEMPLATES/chapter_break.tex \
#    --include-in-header $TEMPLATES/inline_code.tex \
#    --include-in-header $TEMPLATES/bullet_style.tex \
#    --include-in-header $TEMPLATES/listings-setup.tex \

# OPTIONS:

# Use GitHub Flavored Markdown
#    -f gfm \

# Do not center tables
#    --include-in-header $TEMPLATES/no_centered_tables.tex \
